name: Java Setup

on:
  workflow_dispatch:

jobs:
  java-setup:
    runs-on: ubuntu-latest
    steps:
      - name: jdk setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
