name: main
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "Hello world"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Building the project"

  test:
    runs-on: ubuntu-latest
    needs: build                
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running tests"

  deploy:
    runs-on: ubuntu-latest
    needs: test                 
    steps:
      - run: echo "Deploying to production"
