name: Python Setup

on:
  workflow_dispatch:

jobs:
  python-setup:
    runs-on: ubuntu-latest
    steps:
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: run python script
        run: python python_script.py
