name: Nodejs setup

on:
  workflow_dispatch:

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Nodejs script
        run: node app.js
